# Generated by Django 3.0.3 on 2020-03-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodrec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='nutrient_fat_amount',
            new_name='nutrient_sugar_amount',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='nutrient_fat_unit',
            new_name='nutrient_sugar_unit',
        ),
    ]
